### ISSUE TITLE
Symfony Integration

### ISSUE THREAD

**Issue by pueppiblue** [matthiasnoback/broadway-serialization#16]
Is there any reason why symfony integration via bundle has been dropped?
It was trivial to set up `Reconstitution::reconstituteUsing()` this way.
Now i might have to write an extra EventListener/-Subscriber for this.

**Comment by matthiasnoback** [comment]
We'd have to ask @jdrieghe about this. It just isn't much config anyway, see https://github.com/matthiasnoback/broadway-serialization/commit/c91c727fa4488b24cc41068296d0bfde0b2bd69f
With auto-wired services I don't think it will be an inconvenience. You don't need a listener, you can call that static method in your own `boot()` function.

**Comment by jdrieghe** [comment]
@pueppiblue We decided to remove the Symfony bundle integration when we added PHP 8 support due to some incompatibilities with older Symfony versions if I remember correctly.

As Matthias said, it's not too much configuration to integrate with an existing Symfony application as described above.
If you have some time to re-introduce a bundle integration that is compatible with the latest Symfony versions and both PHP 7.4 and PHP 8.0, I'm happy to help review and test it.

**Comment by pueppiblue** [comment]
> We'd have to ask @jdrieghe about this. It just isn't much config anyway, see [c91c727](https://github.com/matthiasnoback/broadway-serialization/commit/c91c727fa4488b24cc41068296d0bfde0b2bd69f) With auto-wired services I don't think it will be an inconvenience. You don't need a listener, you can call that static method in your own `boot()` function.

Yes that tipped me in the right direction. I totally forgot Kernel.php is my "own" class and i can override the parent's `HttpKernel::boot()`.
That should do as a quick workaround.

> As Matthias said, it's not too much configuration to integrate with an existing Symfony application as described above. If you have some time to re-introduce a bundle integration that is compatible with the latest Symfony versions and both PHP 7.4 and PHP 8.0, I'm happy to help review and test it.

Mayhaps it'll come to that given some leisure time. Imo the best approach would be to submit a recipe to `symfony/recipe`.
Thanks a bunch for the prompt replies.
